// <auto-generated />
using BuySellBeater.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuySellBeater.api.Migrations
{
    [DbContext(typeof(BuySellBeaterDBContext))]
    [Migration("20260801142822_SeedMakesAndModels")]
    partial class SeedMakesAndModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuySellBeater.api.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Isuzu"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Honda"
                        });
                });

            modelBuilder.Entity("BuySellBeater.api.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MakeId = 1,
                            Name = "Pup"
                        },
                        new
                        {
                            Id = 2,
                            MakeId = 1,
                            Name = "Impulse"
                        },
                        new
                        {
                            Id = 3,
                            MakeId = 1,
                            Name = "Trooper"
                        },
                        new
                        {
                            Id = 4,
                            MakeId = 2,
                            Name = "Sentra"
                        },
                        new
                        {
                            Id = 5,
                            MakeId = 2,
                            Name = "300ZX"
                        },
                        new
                        {
                            Id = 6,
                            MakeId = 2,
                            Name = "XTerra"
                        },
                        new
                        {
                            Id = 7,
                            MakeId = 3,
                            Name = "CRX"
                        },
                        new
                        {
                            Id = 8,
                            MakeId = 3,
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 9,
                            MakeId = 3,
                            Name = "Prelude"
                        });
                });

            modelBuilder.Entity("BuySellBeater.api.Models.Model", b =>
                {
                    b.HasOne("BuySellBeater.api.Models.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("BuySellBeater.api.Models.Make", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
